/*
 * cambusa-controller
 * Servizio per la tracciatura delle scadenze dei prodotti
 *
 * OpenAPI spec version: 0.0.4
 * Contact: stmsat@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Posizione model module.
 * @module model/Posizione
 * @version 0.0.4
 */
export class Posizione {
  /**
   * Constructs a new <code>Posizione</code>.
   * @alias module:model/Posizione
   * @class
   * @param name {String} 
   */
  constructor(name) {
    this.name = name;
  }

  /**
   * Constructs a <code>Posizione</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Posizione} obj Optional instance to populate.
   * @return {module:model/Posizione} The populated <code>Posizione</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Posizione();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Posizione.prototype.id = undefined;

/**
 * @member {String} name
 */
Posizione.prototype.name = undefined;

