/*
 * cambusa-controller
 * Servizio per la tracciatura delle scadenze dei prodotti
 *
 * OpenAPI spec version: 0.0.4
 * Contact: stmsat@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';
import {Posizione} from './Posizione';
import {Tipo} from './Tipo';

/**
 * The Prodotto model module.
 * @module model/Prodotto
 * @version 0.0.4
 */
export class Prodotto {
  /**
   * Constructs a new <code>Prodotto</code>.
   * @alias module:model/Prodotto
   * @class
   * @param name {String} 
   * @param dataScadenza {Date} 
   * @param tipo {module:model/Tipo} 
   */
  constructor(name, dataScadenza, tipo) {
    this.name = name;
    this.dataScadenza = dataScadenza;
    this.tipo = tipo;
  }

  /**
   * Constructs a <code>Prodotto</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Prodotto} obj Optional instance to populate.
   * @return {module:model/Prodotto} The populated <code>Prodotto</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Prodotto();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('dataScadenza'))
        obj.dataScadenza = ApiClient.convertToType(data['dataScadenza'], 'Date');
      if (data.hasOwnProperty('tipo'))
        obj.tipo = Tipo.constructFromObject(data['tipo']);
      if (data.hasOwnProperty('posizione'))
        obj.posizione = Posizione.constructFromObject(data['posizione']);
      if (data.hasOwnProperty('aperto'))
        obj.aperto = ApiClient.convertToType(data['aperto'], 'Boolean');
      if (data.hasOwnProperty('dataApertura'))
        obj.dataApertura = ApiClient.convertToType(data['dataApertura'], 'Date');
      if (data.hasOwnProperty('quantita'))
        obj.quantita = ApiClient.convertToType(data['quantita'], 'Number');
      if (data.hasOwnProperty('dataScadenzaGenerata'))
        obj.dataScadenzaGenerata = ApiClient.convertToType(data['dataScadenzaGenerata'], 'Date');
    }
    return obj;
  }
}

/**
 * @member {String} id
 */
Prodotto.prototype.id = undefined;

/**
 * @member {String} name
 */
Prodotto.prototype.name = undefined;

/**
 * @member {Date} dataScadenza
 */
Prodotto.prototype.dataScadenza = undefined;

/**
 * @member {module:model/Tipo} tipo
 */
Prodotto.prototype.tipo = undefined;

/**
 * @member {module:model/Posizione} posizione
 */
Prodotto.prototype.posizione = undefined;

/**
 * @member {Boolean} aperto
 */
Prodotto.prototype.aperto = undefined;

/**
 * @member {Date} dataApertura
 */
Prodotto.prototype.dataApertura = undefined;

/**
 * @member {Number} quantita
 */
Prodotto.prototype.quantita = undefined;

/**
 * @member {Date} dataScadenzaGenerata
 */
Prodotto.prototype.dataScadenzaGenerata = undefined;

