/*
 * cambusa-controller
 * Servizio per la tracciatura delle scadenze dei prodotti
 *
 * OpenAPI spec version: 0.0.4
 * Contact: stmsat@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.42
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Posizione} from './model/Posizione';
import {Prodotto} from './model/Prodotto';
import {Tipo} from './model/Tipo';
import {CambusaControllerApi} from './api/CambusaControllerApi';
import {CambusaControllerDevelApi} from './api/CambusaControllerDevelApi';

/**
* Servizio_per_la_tracciatura_delle_scadenze_dei_prodotti.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CambusaController = require('index'); // See note below*.
* var xxxSvc = new CambusaController.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CambusaController.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CambusaController.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CambusaController.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.4
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Posizione model constructor.
     * @property {module:model/Posizione}
     */
    Posizione,

    /**
     * The Prodotto model constructor.
     * @property {module:model/Prodotto}
     */
    Prodotto,

    /**
     * The Tipo model constructor.
     * @property {module:model/Tipo}
     */
    Tipo,

    /**
    * The CambusaControllerApi service constructor.
    * @property {module:api/CambusaControllerApi}
    */
    CambusaControllerApi,

    /**
    * The CambusaControllerDevelApi service constructor.
    * @property {module:api/CambusaControllerDevelApi}
    */
    CambusaControllerDevelApi
};
